CREATING A TABLE IN MYSQL
	
A database schema is first created before the table is created.

	
Schema

Schema are the blue prints of databases. It shows a database design such as what tables are included in the database and any relationship btw its tables. 
It lets one know what data type each field can hold.

A key is one or more columns that are identified as such in the creation of a table. 
Primary key is used to ensure data in the specific column is unique (identifies each record), it cannot be null and It is either an existing table column or a column that is specifically generated by the database according to a defined sequence. A table can only have one primary key because it defines the entity

Foreign key is a column or group of columns in a relational database table that provides a link between data in two tables. It is a column (or columns) that references another column (most often the primary key) of another table.  For a foreign key to exist in one entity, it must be the primary key in a related entity.  The main requirement of foreign keys is the establishment of relationships between.  It makes sure that, data is linked across multiple tables and helps in storing and retrieving data. We need foreign keys as they help us make sure that data is consistent, complete between both the tables and overall accuracy is maintained (data integrity).
                   


	
TABLE CREATION PORCEDURE
	
A database schema is first created before the table is created.
Right click on database on the left hand of MYSQL work bench and click on create schema (MYSQL)
This creates a new_schema tab	
Name the schema, click on apply and finish.
You would find it below database on the left of the screen
Click on the schema, then right click on table, click on create table
A new table tab pops up
Name the table, fill the column names and the datatypes. You can also select your primary key here. Click on apply and finish.

Click on table, click on the table name, click on the symbol i, this opens the table. 
Go to ddl, copy the syntax and paste on a new query tab to create the table.


To alter the schema(table), right click on the table name and click on alter table
make the necessary changes and click on apply
to get the current schema, click on the table name, double click on the box (note the modification on the table name,it is now together with the schema name)
use it going forward. see ogenelly schema on MYSQL.
click on edit to input your data manually instead of usin the insert statement.

Synthax:
	
--    CREATE TABLE table_name (
--      Column 1 datatype,
--      Column 2 datatype,
--      Column 3 datatype,
--      Column 4 datatype,
--       ...
--     );

-- The table can now be filled with data using the MYSQL INSERT INTO Statement:
	
               INSERT INTO DATABASE (Colunmn1, Colunmn2, Colunmn3, Colunmn4)
                 VALUES ('CUPCAKE','WHITE WAY','TORONTO','ONTARIO','112');



CREATE TABLE `posbusiness` (
  `id` int NOT NULL,
  `MONTH` varchar(45) DEFAULT NULL,
  `EXPENSE_ITEM` varchar(45) DEFAULT NULL,
  `COST_OF_EXPENSE_ITEM` varchar(45) DEFAULT NULL,
  `TOTAL MONTHLY SALES` varchar(45) DEFAULT NULL,
  `TOTAL MONTHLY EXPENSE` varchar(45) DEFAULT NULL,
  `PROFIT` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
);
DESC posbusiness;

SELECT * FROM posbusiness;                                     -- selects all the column

SELECT * FROM ogenellyfamily.posbusiness;                      -- GIVES U A TABLE TO INPUT MANUALLY (NO NEED FOR INSERT STATEMENT)
                                                                         HERE WE ARE USING BOTH THE SCHEMA NAME AND THE TABLE NAME 


-- Below is the Table syntax:

   --             CREATE TABLE table_name (
   --     column1 datatype constraint,
   --     column2 datatype constraint,
   --     column3 datatype constraint
   -- );


CREATE TABLE `umuogenelly` (
  `id` int NOT NULL,
  `name` varchar(45) DEFAULT NULL,
  `sex` varchar(45) DEFAULT NULL,
  `date_of_birth` varchar(45) DEFAULT NULL,
  `name_of_university` varchar(45) DEFAULT NULL,
  `realationship` varchar(45) DEFAULT NULL,
  `day_of_birth` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
);
DESC umuogenelly;                                               #shows the primary key, the column, data types

INSERT INTO  umuogenelly VALUES(1,'PRINCE','MALE','29-06-2022','HUMBER_COLLEGE','SON','THURSDAY');
INSERT INTO  umuogenelly VALUES(2,'OGECHI','FEMALE','05-03-1998','FEDEI_POLY','WIFE','FRIDAY');
INSERT INTO  umuogenelly VALUES(3,'NELSON','MALE','28-01-1985','UNIVERSITY_OF_JOS','HUSBAND','MONDAY');




--                           *FROM CLAUSE example
-- Selecting columns

SELECT NAME FROM umuogenelly;                                   -- selects specific column(field names) from the table for all the record
SELECT NAME, Sex FROM umuogenelly;

SELECT * FROM umuogenelly;                                      -- selects all the column(field names) available in the table 

                                           








--                           *WHERE CLAUSE example

 -- Selecting specific record
 
SELECT * FROM umuogenelly WHERE NAME = 'NELSON';                 
SELECT * FROM umuogenelly WHERE NAME = 'PRINCE';
SELECT * FROM umuogenelly WHERE NAME = 'ogechi';

SELECT * FROM umuogenelly WHERE NAME = NULL;
SELECT * FROM umuogenelly WHERE NAME IS NULL;
SELECT * FROM umuogenelly WHERE NAME IS NOT NULL;
SELECT * FROM umuogenelly WHERE DATE_OF_BIRTH is null;


--                           *ORDER BY CLAUSE example

-- Selects the arrangement of the records alphabetically

SELECT * FROM umuogenelly ORDER BY NAME;
SELECT * FROM umuogenelly ORDER BY date_of_birth ;
SELECT * FROM umuogenelly ORDER BY NAME DESC;




                           TABLE MODIFICATION
	               ----------------------------

CREATE TABLE `umuogenelly2` (
  `age` int NOT NULL,
  `name` varchar(45) DEFAULT NULL,
  `surname` varchar(45) DEFAULT NULL,
  `gender` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`age`)
);
INSERT INTO  umuogenelly2 VALUES('2', 'PRINCE','OKOLIE', 'MALE');
INSERT INTO  umuogenelly2 VALUES('24', 'OGECHI','OKOLIE', 'FEMALE');
INSERT INTO  umuogenelly2 VALUES('37', 'NELSON', 'OKOLIE','M');

SELECT * FROM umuogenelly2;

SELECT NAME FROM umuogenelly2; 
SELECT SURNAME FROM umuogenelly2; 



--                          A. ADDING ROWS
                                 -----
INSERT INTO  umuogenelly2 (age,name,surname,gender) VALUES (1,'SUNSHINE','OKOLIE','FEMALE');
INSERT INTO  umuogenelly2 (age,name,surname,gender) VALUES (3,'notnamed','okolie','MALE');

SELECT * FROM umuogenelly2;

 -- DELETING ROWS



--                          B. ADDING COLUMNS
                                  -------
ALTER TABLE umuogenelly2                                   -- nb no semicolon on the first line
Add year_of_birth INT;

SELECT * FROM umuogenelly2;

--                           C. DELETING COLOUMNS

ALTER TABLE umuogenelly2
DROP COLUMN gender;

SELECT * FROM umuogenelly2;

--                           D. RENAMING COLUMNS
Syntax:
ALTER TABLE table_name
RENAME COLUMN old_name to new_name;


ALTER TABLE umuogenelly2
RENAME COLUMN name to afa;

SELECT * FROM umuogenelly2;

--                          

                                E. CHANGING DATA TYPE OF COLUMNS IN A TABLE
ALTER TABLE umuogenelly2
MODIFY COLUMN surname TEXT;

SELECT * FROM umuogenelly2;











